#!/usr/bin/env sh

yabai -m rule --add app="^OBS$" layer=above manage=off
yabai -m rule --add app="^Bear$" layer=above manage=off
yabai -m rule --add app="^Home$" layer=above manage=off
yabai -m rule --add app="^zoom.us$" layer=above manage=off
yabai -m rule --add app="^Camo Studio$" layer=above manage=off
yabai -m rule --add app="^Zoom$" layer=above manage=off
yabai -m rule --add app="^Photo Booth$" layer=above manage=off
yabai -m rule --add app="^FaceTime$" layer=above manage=off
yabai -m rule --add app="^CleanShot X$" layer=above manage=off
yabai -m rule --add app="^CleanMyMac X$" layer=above manage=off
yabai -m rule --add app="^App Store$" layer=above manage=off
# yabai -m rule --add app="^Umbra$" layer=above manage=off
yabai -m rule --add app="^System Preferences$" layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" layer=above manage=off
yabai -m rule --add app="^Finder$" layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" layer=above manage=off
yabai -m rule --add app="^Spotify$" layer=above manage=off
yabai -m rule --add app="^Discord$" layer=above manage=off
yabai -m rule --add app="^Umbra$" layer=above manage=off

# yabai -m config mouse_follows_focus          off
# yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                off
yabai -m config window_opacity               off
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.50
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  14
yabai -m config bottom_padding               14
yabai -m config left_padding                 14
yabai -m config right_padding                14
yabai -m config window_gap                   16

yabai -m config debug_output on


killall /usr/local/bin/limelight &> /dev/null

/usr/local/bin/limelight &> /dev/null &


echo "yabai configuration loaded.."
